### PR TITLE
Bug fixes & Enhancement

### PR DESCRIPTION
**Pull request by krishandroiddev**

### CODE REVIEW

**Comment by DevVigilante** [comment]
@krishandroiddev thanks for the improvement ❤️
Actually I didn't checked out that dark mode was not working.

**Comment by CyberGlitch01** [comment]
@DevKumar00001 Can you give a little time for add a code generator in attachment blocks so that I can design blocks?

**Comment by DevVigilante** [comment]
> @DevKumar00001 Can you give a little time for add a code generator in attachment blocks so that I can design blocks?

@CyberGlitch01 done for Blocks but not for conplex blocks as for them attachment blocks for not compatible (9 patch images have not been created yet.

**Comment by DevVigilante** [comment]
Everything done??
Can I merge this?

**Pull request merged**
